import streamlit as st
from datetime import date, timedelta
from PIL import Image

from src.config import BACKGROUND_STYLE
from src.visualization.charts import prepare_chart_data, generate_chart_image
from src.agents.stocks_agent import FinancialAgent  # מיקום הסוכן – וודא שהנתיב נכון

# Apply background style
st.markdown(BACKGROUND_STYLE, unsafe_allow_html=True)

# Load logo and title
try:
    col1, col2 = st.columns([1, 6])
    with col1:
        logo = Image.open("image.png")
        st.image(logo, width=60)
    with col2:
        st.markdown("<h1 style='margin-top: 15px;'>Smart Stock Comparison</h1>", unsafe_allow_html=True)
except Exception as e:
    st.warning(f"Error loading logo: {e}")

# Language selection
language = st.radio("Language / שפה", ["English", "עברית"], horizontal=True)

# Create an instance of the FinancialAgent (using appropriate language code)
agent = FinancialAgent(language="he" if language == "עברית" else "en")

# Input form for tickers and dates
with st.form("stock_form"):
    tickers_input = st.text_input(
        "הזן טיקרי מניות (מופרדים בפסיק):" if language == "עברית" 
            else "Enter stock tickers (comma-separated):",
        "AAPL, MSFT, TSLA"
    )
    # Note: The agent uses a fixed 1-year period internally.
    # The date inputs below can be used for display purposes if needed.
    start_date = st.date_input(
        "תאריך התחלה" if language == "עברית" else "Start Date",
        date.today() - timedelta(days=365)
    )
    end_date = st.date_input(
        "תאריך סיום" if language == "עברית" else "End Date",
        date.today()
    )
    submitted = st.form_submit_button("השווה" if language == "עברית" else "Compare")

if submitted:
    # Use the agent to analyze the stocks.
    result = agent.analyze_stocks(tickers_input)
    if "error" in result:
        st.error(result["error"])
    else:
        # Display statistics table
        st.subheader("טבלה" if language == "עברית" else "Table")
        st.dataframe(result["stats_table"])
        
        # Display Smart Analysis text
        st.subheader("ניתוח חכם" if language == "עברית" else "Smart Analysis")
        if language == "עברית":
            st.markdown(f"<div dir='rtl' style='text-align: right;'>{result['analysis_text']}</div>", unsafe_allow_html=True)
        else:
            st.markdown(result["analysis_text"])
        
        # Generate and display chart based on the price data returned by the agent
        if "price_df" in result:
            price_df = result["price_df"]
            
            st.subheader("אפשרויות גרף" if language == "עברית" else "Chart Options")
            if language == "עברית":
                time_options = {"מצטבר": "Cumulative", "חודשי": "Monthly", "רבעוני": "Quarterly", "שנתי": "Yearly"}
                selected_time_label = st.selectbox("בחר חתך זמן", list(time_options.keys()), key="time_interval")
                selected_time_interval = time_options[selected_time_label]
            else:
                selected_time_interval = st.selectbox(
                    "Select Time Interval",
                    ["Cumulative", "Monthly", "Quarterly", "Yearly"],
                    key="time_interval"
                )
            
            selected_chart_type = st.radio(
                "בחר סוג גרף" if language == "עברית" else "Select chart type",
                ["Line", "Bar"],
                key="chart_type"
            )
            selected_display_mode = st.radio(
                "בחר מצב תצוגה" if language == "עברית" else "Select display mode",
                ["Normalized", "Return"],
                key="display_mode"
            )
            
            chart_data = prepare_chart_data(price_df, selected_time_interval, selected_display_mode)
            st.subheader("גרף" if language == "עברית" else "Chart")
            if selected_chart_type == "Line":
                st.line_chart(chart_data)
            else:
                st.bar_chart(chart_data)
            
            # Generate chart image for PDF export
            chart_image = generate_chart_image(chart_data, selected_chart_type)
        else:
            st.warning("Price data not available for chart generation.")
        
        # PDF download button using the PDF report generated by the agent
        st.download_button(
            label="📄 ייצוא ל-PDF" if language == "עברית" else "📄 Export to PDF",
            data=result["pdf_report"].getvalue(),
            file_name="financial_report.pdf",
            mime="application/pdf",
            use_container_width=True,
            key="download_pdf_button"
        )
